### ISSUE TITLE
Fix Spelling and Layout Mistakes in Guide Book

### ISSUE THREAD

**Issue by Tacodude7729** [Tacodude7729/totemic-overhaul#1]
Book is title: 'guid' not 'guide'.

**Comment by Ravio31668** [comment]
Active Totems chapter, page 1: 'usful' not 'useful'.

**Comment by Ravio31668** [comment]
Passive Totems chapter: 'durabilty' not 'durability', 'wich' not 'which'.

**Comment by Ravio31668** [comment]
Activators chapter, page 1: 'These' needs to be changed to 'This' or 'ranges' needs to be changed to 'range', 'combine' not combined'.

**Comment by Tacodude7729** [comment]
Fixed in #3
